NAME : grader

VARS : 
  DIR : "/grader/"
  msg : "hello"
  cont_name : grader


EXECUTE :
  - PRINT "# copying to server..."
  - RUN server "mkdir -p /server_results"
  - STORECMD server_ip server "hostname -i"
  - RUN server "rm -f /server_results/log1.txt"
  - RUN server "touch /server_results/log1.txt"
  - RUN "server" "g++ /app/SimpleEmailServerPhase1.cpp -o /s1.out" 
  - RUN -d server "/s1.out 5555 /app/passwd.txt > /server_results/log1.txt"

  - SLEEP "0.5"

  - PRINT "# copying to client..."
  - COPY "/grader/testcase1.txt" "client:/"
  - COPY "/grader/client_evaluate.sh" "client:/"
  - RUN "client" "bash /client_evaluate.sh {server_ip}:5555 /testcase1.txt"

  - PRINT "# Collecting results..."
  - SLEEP 0.5
  - PRINT "..."
  - SLEEP 0.5

  - RUN grader "mkdir -p obtained_results"
  - RUN grader "mkdir -p obtained_results/testcase1"
  - COPY "server:/server_results/log1.txt" "/grader/obtained_results/testcase1/server.txt"
  - COPY "client:/client_results/log1.txt" "/grader/obtained_results/testcase1/client.txt"
  
  - PRINT ""
  - PRINT "========== server log ==========="
  - PRINT ""
  - PRINT -f "/grader/obtained_results/testcase1/server.txt"
  - PRINT ""
  - PRINT "========== client log ==========="
  - PRINT ""
  - PRINT -f "/grader/obtained_results/testcase1/client.txt"
  - PRINT ""
  - PRINT "========== results ============="
  - RUN grader "bash /grader/testcase_evaluate.sh"
  - PRINT ""
  # - PRINT "{msg} {cont_name}"
  # - RUN grader 'echo {msg} from grader {server_ip}'
