# Generated by Django 4.2.2 on 2023-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_gradermount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
