# Generated by Django 4.2.2 on 2023-10-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_lab_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='description',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
